# Streamlit Configuration

[theme] # You have to add this line
primaryColor = "#1f77b4"  # Darker blue
backgroundColor = "#041E42"  # Dark background
secondaryBackgroundColor = "#63666A"  # Slightly lighter background
textColor = "#ecf0f1"  # Light text color
font = "sans serif"

